version: 2.0
jobs:
  build_debug:
    docker:
      - image: urnm1/devenv:latest
    steps:
      - checkout
      - run: conan install .
      - run:
          command: cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
          working_dir: build
      - run:
          command:  cmake --build .
          working_dir: build
  build_release:
    docker:
      - image: urnm1/devenv:latest
    steps:
      - checkout
      - run: conan install .
      - run:
          command: cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          working_dir: build
      - run:
          command:  cmake --build .
          working_dir: build
    
workflows:
  version: 2
  build_debug-and-test:
    jobs:
      - build_debug
#      - test:
#          requires:
#            - build_debug
  build_release-and-upload_to_github:
    jobs:
      - build_release
#      - upload_to_github:
#          requires:
#            - build_release
