version: 2.0
jobs:
  build_debug:
    docker:
      - image: urnm1/devenv:latest
    filters:
      branches:
        only: master
    working_directory: ~/project
    environment:
      CC=/usr/bin/gcc
      CXX=/usr/bin/g++
    steps:
      - checkout
      - restore_cache:
          keys:
            - conan-cache-v2--{{ checksum "conanfile.txt" }}
            - conan-cache-v2
      - run:
          command: conan install .. -s build_type='Debug' -s compiler=gcc -s compiler.version=9 -s compiler.libcxx='libstdc++11' -g=cmake -b=missing 
          working_directory: build
      - save_cache:
          paths:
            - ~/.conan
          key: conan-cache-v2--{{ checksum "conanfile.txt" }}
      - run:
          command: cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
          working_directory: build
      - run:
          command:  cmake --build .
          working_directory: build
workflows:
  version: 2
  build_debug-and-test:
    jobs:
      - build_debug
