version: 2.0
jobs:
  build_debug:
    docker:
      - image: urnm1/devenv:latest
    filters:
      branches:
        only: master
    working_directory: ~/project
    environment:
      CC=/usr/bin/gcc-9
      CXX=/usr/bin/gcc+9
    steps:
      - checkout
      - restore_cache:
        keys:
          - conan-cache-v1--{{ checksum "conanfile.py" }}
          - conan-cache-v1
          
      - run:
          command: conan install .. -s build_type=Debug
          working_directory: build
      - save_cache:
        paths:
          - ~/.conan
        key: conan-cache-v1--{{ checksum "conanfile.py" }}
      - run:
          command: cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
          working_directory: build
      - run:
          command:  cmake --build .
          working_directory: build
workflows:
  version: 2
  build_debug-and-test:
    jobs:
      - build_debug
#      - test:
#          requires:
#            - build_debug
#  build_release-and-upload_to_github:
#    jobs:
#      - build_release
#      - upload_to_github:
#          requires:
#            - build_release
